version: "3.8"
networks:
    portfolio-network:
        external: true
services:
  mongodb:
    image: mongo
    container_name: portfolio-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    ports:
    - 27020:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks: 
      - portfolio-network


    